FROM python:3.8-alpine 

RUN apk update && apk add bash nmap nmap-scripts

# Copy requirements and install 
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Start the Application  
EXPOSE 80
COPY ./app /app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]