FROM kalilinux/kali-rolling:latest


RUN apt-get update && apt-get install -y git build-essential libssl-dev zlib1g-dev yasm libgmp-dev libpcap-dev libbz2-dev libgomp1 python3 python3-pip john

# Copy requirements and install 
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Start the Application  
EXPOSE 80
COPY ./app /app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]